TykTechnologies/gromit

policy/templates/releng/.github/dependabot.yml
Pump has a dependabot PR flow configured for go.mod update. This PR updates the corresponding releng templates  so that it's persisted across further renders of the template.
=> Update dependabot template for pump.

policy/templates/releng/.github/dependabot.yml
Update the releng template for dependabot to include `go mod` dependencies.
=> Update dependabot template for tib.

policy/templates/releng/ci/goreleaser/goreleaser-el7.yml.d/nfpm.tmpl, policy/templates/releng/ci/goreleaser/goreleaser.yml.d/nfpm.tmpl
Portal has a bunch of directories which it depends on for proper installation and running.
The nfpm path was set mistakenly before which led to not having the entire directory tree present. 
This PR fixes this issue.
=> Fix the nfpm contents path for portal.

policy/templates/sync/.github/workflows/sync-automation.yml, testdata/sync-automation/sync-automation.yml
API tests are not available in all repos. Also the file names change across repos for api tests. Try to handle this for the repos under management.
example of failed sync here: https://github.com/TykTechnologies/tyk-identity-broker/actions/runs/3061029819/jobs/4940284159#step:3:53
=> Fix some invalid paths in sync-automation.

policy/policy.go, policy/templates/releng/.github/dependabot.yml, testdata/policies/repos.yaml
For dependabot, and other auto generated PRs, it would be nice to have a list of reviewers who could be assigned to review these PRs once these are generated.
This PR adds the functionality to gromit. More details in [TD-1168]
[TD-1168]: https://tyktech.atlassian.net/browse/TD-1168?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [TD-1168]: Add reviewers to gromit policy.

policy/policy_test.go
The go version change for master branch was making this test fail. 
This change updates the test data to fix this.
=> Fix the policy test.

config/config.yaml
Release notes are now filled with JIRA, commit message linter is obsolete, removing.
https://tyktech.atlassian.net/browse/TT-7456
Blocking https://github.com/TykTechnologies/tyk-analytics/pull/2886
=> Remove commit message linter from required checks

policy/templates/releng/ci/Dockerfile.std
Reduce Ensure that curl is removed when it no longer needed. At the moment it accounts for a few critical/high vurneabilities flagged by dockerhub.
=> [TT-7642] Reduce CVE surface by removing cURL

policy/templates/sync/.github/workflows/sync-automation.yml
Use the ITS token for checkout and gh invocation only - all the other git actions we do are
specific to the repo and the GITHUB_TOKEN has the required repo permissions to do them.
=> Use GH_TOKEN for gh cli

policy/templates/sync/.github/workflows/sync-automation.yml
Review requests for TykTechnologies/devops are
already assigned as a result of having appropriate CODEOWNERS entry.
=> [TD-1474]:Remove review request step from sync-automation

git/git.go
Due to go-git issue #305
(https://github.com/go-git/go-git/issues/305) - pulling on shallow clone leads to object not found error.
=> Disable pulling on git init

config/config.yaml
Updated the policy about which tests are required to merge into the dashboard master branch and release-5-lts. The check `mongo` not longer exist, and now we have 2: mongo-official and mongo-mgo given that the work of storages has been merged
=> updated the required tests in dahsboard for master and release-5-lts

policy/templates/releng/.github/workflows/release.yml.d/goreleaser.tmpl
Latest portal changes bumps the goreleaser action version to 4. With goreleaser-action at v4 and if checkout is shallow - it looks like goreleaser fails if --snapshot isn't explicitly set in case the trigger isn't a tag push.
Updates the templates to include the fix for this.
=> Update goreleaser command in release.yml - releng templates

config/config.yaml, policy/templates/releng/.github/workflows/release.yml.d/goreleaser.gotmpl
Restore the fix vendor step in release workflow, which is required
for plugin compiler compatibility for all the branches before the
go 1.19 change.
The templates use the go1.19 feature to conditionally add this
step.
=> [TD-2105]: Restore Fix vendor step

policy/templates/releng/ci/goreleaser/goreleaser.yml.d/dockers.gotmpl
semver versioning has the concept of build numbers, where the same {{Major}}.{{Minor}}.{{Patch}} versions can have incremental revisions/builds with higher build numbers getting higher version precedence( eg: 1.2.3+b2 > 1.2.3+b2).
Docker tags don't support '+' in it, and this PR does an inline replace for this case in goreleaser config.
=> [TD-2096]: Add replace directives to support build numbers

policy/templates/releng/.github/workflows/release.yml.d/goreleaser.gotmpl
This PR is aimed to rework the tag for CI images, so repo can be clean out by using policy based on prefixes
=> SYSE-274/Change tag policy for ci images

config/config.yaml
A docs sync action was triggered from 4-lts and is unwanted. This policy change adds `update-config-docs.yml` action to the deletedfiles definition.
It looks like [SYSE-292](https://tyktech.atlassian.net/browse/SYSE-292) was commited but not applied for 4-LTS (yet?). I opened a PR removing the actions on 4-LTS and decided to update the policies if there are other target branches to clean up.
Via: https://github.com/TykTechnologies/tyk/pull/5931
[SYSE-292]: https://tyktech.atlassian.net/browse/SYSE-292?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add old update-config-docs.yml to deletedfiles policies

config/config.yaml, policy/policy.go, policy/templates/releng/.github/workflows/release.yml.d/smoke-tests.gotmpl
tyk-sink has a different packagecloud repo name format from the other repos. Handle this conditionally in the upgrade tests templates.
Also removes PCPrivate variable since we don't have any private packagecloud repos anymore.
=> Releng templates: Add repo name conditional for tyk-sink in upgrade tests

policy/templates/subtemplates/auto/api-tests.gotmpl
Set pipefail to fix regression tests not reporting any failure. This is critical
=> set pipefail

config/config.yaml
An incorrect path was listed in dashboard for the version package, this PR corrects the path.
Should be applied to tyk-analytics 5-LTS and 5.3/master, for the upcoming 5.3.0 and 5.0.11 releases.
=> Fix version package for tyk-dashboard

policy/templates/subtemplates/auto/api-tests.gotmpl, policy/templates/subtemplates/auto/ui-tests.gotmpl
`Override` doesn't seem to be a valid option for upload-artifact@v4.
See the warning on the run below:
https://github.com/TykTechnologies/tyk/actions/runs/8262826493/job/22603310931?pr=6138#step:11:1
=> Override isn't a valid input for upload-artifact@v4

config/config.yaml
response for the xz vuln
see https://github.com/TykTechnologies/portal/pull/1206
=> portal uses debian stable now

config/config.yaml
Updates portal go version to 1.21 in master branch. The previous release branch `release-1.8.0` should stay in 1.19
=> Update portal go version

Makefile, policy/templates/releng/.github/workflows/release.yml.d/goreleaser.gotmpl
Fix plugin compiler support for `release-5-lts`.
We already have the feature `plugin-compiler-fix-vendor` feature added to the release-4-lts and release-5-lts config. So using that instead of the suffix check.
=> SYSE-356: Fix plugin compiler support for lts branches

config/config.yaml, policy/templates/el7/ci/goreleaser/goreleaser-el7.yml.d/builds.gotmpl, policy/templates/el7/ci/goreleaser/goreleaser-el7.yml.d/cgo_builds.tmpl, policy/templates/releng/.github/workflows/release.yml.d/goreleaser.gotmpl, policy/templates/releng/ci/Dockerfile.std
- It appears gateway doesn't need separate el7 conditionals at all - so adds the el7 feature only to dashboard, and change the conditionals accordingly.
- s390x feature conditions were not set for the goreleaser.el7 templates, fixes it as well.
- Adds a new feature python-support to conditionally manage python plugin support in gateway
=> [SYSE-337]: Fixes in el7, and s390x feature conditions

go.mod, go.sum, policy/github.go
Existing error handling allows the remaining PRs to be created
=> PRs need backing branches

policy/templates/el7-pgo-build/ci/goreleaser/goreleaser-el7.yml, policy/templates/releng/ci/goreleaser/goreleaser.yml, policy/templates/subtemplates/goreleaser.yml.d/cgo_builds.gotmpl
- Removes version for goreleaser over 1.16 builds
- Include tags 'goplugin' and 'trim' for all builds
=> Fix release-5-lts goreleaser build

policy/templates/subtemplates/auto/auto-test.gotmpl
Missing reference on execution step is preventing metadata generation step to run
=> SYSE-396/Fix metadata report ui test step

config/config.yaml, policy/templates/releng/.github/workflows/release.yml.d/goreleaser.gotmpl
changed buildenv  for cgo-services from "buildenv: 1.21-bullseye" to "buildenv: 1.22-bookworm"
=> TT-12815,  upgrade to golang 1.22

policy/templates/releng/.github/workflows/release.yml.d/goreleaser.gotmpl
https://github.com/TykTechnologies/tyk/issues/6517
=> [SYSE-398] Delete v5 tag and do not push v{{Major}} tags

Makefile, policy/app/index.html, policy/templates/releng/.github/workflows/release.yml, policy/templates/test-square/.github/workflows/test-square.yml, policy/tui.go, policy/tui_test.go, policy/variations.go, testdata/tui/prod-variations.yml
There are 6+ repos and this might increase. We have only two test suites. Making the hierarchy of the tui config format testsuite→branch→trigger→repo reduces the amount of repetition.
The UI remains the same as does the API. However, the config format has changed and will need to be updated when this is merged to master. The tui config file that goes along with this PR is http://tui.internal.dev.tyk.technology/show/inverted.yml
=> invert tui config file to reduce repetition

policy/templates/subtemplates/auto/auto-test.gotmpl
Add using of $BASE_REF in checkout action. $BASE_REF is declared is defined at the top of template and seems to work fine with push/pull/tag event triggers
=> [QA-1539] Make checkout test code to use proper branch/tag

config/config.yaml
PR does the following:
- Disables CGO for analytics master (5.7), for https://github.com/TykTechnologies/tyk-analytics/pull/4187
- Adds release-tests to run release-test.yml
Intended for 5.7+
JIRA: https://tyktech.atlassian.net/browse/TT-13027
Status:
Other changes rendered with policy sync that have been excluded (fetch-depth, ref, some other playwright report related changes). Release 5.6 doesn't seem up to date.
Verified like so:
```
00c04465199a65decbe35c851e98ac93482f93effe3b07634c38067121390204
Successfully copied 304MB to /root/tyk/tyk-analytics/.
tyk-analytics: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, Go BuildID=ZvM4eTnjYk1pZ0YB6Dwr/plXZoibAstfVmX-c8Xxo/NV2VflEy_SnIGsIw7nWt/mXi79XZm-O-GJ2UELuIa, with debug_info, not stripped
```
=> [TT-13027] dashboard: disable CGO, add release-test to master

config/config.yaml, policy/policy_test.go, policy/templates/releng/.github/workflows/release.yml.d/goreleaser.gotmpl, policy/tfuncs.go
Previously, the `GetImages` template function was on the RepoPolicy object and would iterate over the builds to find the image names. This is a bug because we need the image names for a build, not just any image names.
This was addressed by making the GetImages a method of the `build` object. A similar change was made for `GetDockerPlatforms`.
=> [SYSE-403] docker image names from builds object

.github/workflows/release.yml
Previously, when tyk-pro lived in tyklabs, a different token was required to access it.
=> tyk-pro is part of the TykTechnologies org
