testdata/policies/repos.yaml
Add the releng policies  tyk-identity-broker, tyk-sink and portal.
=> Add policies for tib, portal and mdcb.

Dockerfile, Makefile, cmd/policy.go, cmd/root.go
=> Added reference to source code location in log messages

policy/templates/releng/.github/dependabot.yml, policy/templates/releng/ci/goreleaser/goreleaser.yml.d/before_hooks.tmpl, policy/templates/releng/ci/goreleaser/goreleaser.yml.d/nfpm.tmpl
=> Update templates to align with latest portal changes.

policy/templates/releng/ci/goreleaser/goreleaser-el7.yml, policy/templates/releng/ci/goreleaser/goreleaser-el7.yml.d/before_hooks.tmpl, policy/templates/releng/ci/goreleaser/goreleaser-el7.yml.d/nfpm.tmpl
Adds the before hooks and nfpm file list changes to el7 version of goreleaser config.
=> Added el7 changes for portal.

policy/templates/sync/.github/workflows/sync-automation.yml, testdata/policies/repos.yaml
=> Update sync bundle for tyk-analytics.

policy/terraform/github/main.tf
Release branches are created here as well.
=> [TD-1317] Added tyk-analytics-ui

testdata/policies/repos.yaml, testdata/sync-automation/sync-automation.yml
* Remove port-forward from master to release-4.2 (gw and dashboard)
* Add port-forward from master to release-4.3 (gw and dashboard)
=> remove release 4.2 add 4.3 to ports

config/config.yaml
Added:
- `release-4.0.11` from release-4-lts
- `release-4.3.2` from release-4.3
=> Create 4.0.11 and 4.3.2

cmd/bundle.go, cmd/policy.go, cmd/root.go, config/config.go, config/config.yaml, git/diff.go, policy/policy.go, policy/policy_test.go, policy/templates/releng/.github/workflows/release.yml, policy/templates/releng/.github/workflows/release.yml.d/goreleaser.tmpl, policy/templates/releng/ci/goreleaser/goreleaser-el7.yml.d/plugin_compiler.tmpl, policy/templates/releng/ci/goreleaser/goreleaser.yml.d/dockers.tmpl, policy/templates/releng/ci/goreleaser/goreleaser.yml.d/nfpm.tmpl, testdata/policies/repos.yaml
Add multiple version support to  releng templates based on a policy key named `RelengVersion`
=> [TD-968]: Multiple version support.

policy/templates/releng/.github/workflows/release.yml.d/tests.tmpl, policy/templates/releng/ci/goreleaser/goreleaser-el7.yml.d/plugin_compiler.tmpl, policy/templates/releng/ci/goreleaser/goreleaser.yml.d/dockers.tmpl
To include changes from 
- https://github.com/TykTechnologies/tyk/pull/4779
- https://github.com/TykTechnologies/tyk/pull/4701
=> [TD-1528]: Update release workflow templates.

Makefile, config/config.yaml
Update terraform manifest for release 5 branches
=> Add relase 5 branches

config/config.yaml, taskfile.yml
Update tib config to match go update
=> Upgrade tib config 2

policy/templates/releng/.github/workflows/release.yml, policy/templates/releng/.github/workflows/release.yml.d/sbom.tmpl
Based on https://github.com/TykTechnologies/tyk-analytics/pull/3021/files#diff-87db21a973eed4fef5f32b267aa60fcee5cbdf03c67fafdc2a9b553bb0b15f34
=> Added SBOM job

policy/templates/releng/.github/workflows/release.yml.d/goreleaser.tmpl, policy/templates/sync/.github/workflows/sync-automation.yml
Authenticate using ORG_GH_TOKEN for gromit git push invocations.
=> [TD-1648]: Set GITHUB_TOKEN for gromit push commands

config/config.yaml, testdata/policies/repos.yaml
Updating Tyk-pump Go version to 1.16
https://tyktech.atlassian.net/browse/TT-8314
=> TT-8314 Update tyk-pump go version

config/config.yaml, go.sum, policy/templates/releng/.github/workflows/release.yml.d/ci.tmpl, policy/templates/releng/.github/workflows/release.yml.d/goreleaser.tmpl, policy/templates/releng/.github/workflows/release.yml.d/tests.tmpl, policy/templates/releng/ci/Dockerfile.std, policy/templates/releng/ci/goreleaser/goreleaser.yml.d/archives.tmpl, policy/templates/releng/ci/goreleaser/goreleaser.yml.d/dockers.tmpl, policy/templates/releng/ci/goreleaser/goreleaser.yml.d/nfpm.tmpl, policy/templates/sync/.github/workflows/sync-automation.yml
- Update releng templates to reflect portal 1.19 changes
- Fix the commit message escaping issue in sync-automation
=> [TD-1809]: Update releng templates to reflect portal 1.19 changes

policy/templates/releng/.github/workflows/release.yml.d/goreleaser.tmpl
Adds fix for when goreleaser tag string evaluates to false
=> Gromit, Fix goreleaser

config/config.yaml
=> TD-2151/tyk-sink-2.4

policy/templates/releng/.github/workflows/release.yml, policy/templates/releng/.github/workflows/release.yml.d/goreleaser.gotmpl, policy/templates/releng/.github/workflows/release.yml.d/sbom.gotmpl
This PR is aimed to fix missing image for sbom workflow and tag/manifest docker image push
=> Fix; Manifest and tag push

policy/templates/releng/.github/workflows/release.yml.d/tests.gotmpl
Updates the current workflow to run pro-ha environment
=> SYSE-278/update api-test workflow with mdcb

config/config.yaml
Gateway and dashboard are being updated to use go 1.21, this PR adds the necessary changes to the gromit config.
=> [SYSE-305]: Update config to include go1.21 changes

.github/dependabot.yml, .github/workflows/release.yml
Group all minor go mod bumps.
Group all of the actions version bumps.
=> Group dependabot PRs

Makefile, config/config.yaml, policy/policy.go, policy/policy_test.go, policy/set.go
Supply files or directories that should not exist. Can be customised
at the branch level (additive).
=> [SYSE-292] Implemented deletedfiles config attribute

config/config.yaml
This PR is aimed to delete old files used in the v1 regresion tests api and terraform apply for branch creation before rulesets
=> SYSE-273/Delete-old-files

policy/templates/releng/.github/workflows/release.yml, policy/templates/releng/.github/workflows/release.yml.d/goreleaser.gotmpl, policy/templates/subtemplates/auto/api-tests.gotmpl
=> Fix docker logs and notifications

policy/templates/subtemplates/auto/api-tests.gotmpl, policy/templates/subtemplates/auto/ui-tests.gotmpl
=> More versions to update

policy/templates/releng/ci/Dockerfile.std
remove python support from tyk gateway docker image.
=> [TT-11549] remove python from tyk gateway docker image

policy/templates/subtemplates/auto/ui-tests.gotmpl
This PR converges UI and API environments into pro-ha finally
=> Update ui tests to use pro-ha environment

policy/controller.go, policy/controller_test.go
This PR adjust the policy accordingly to the agreed compatibility matrix
=> Adjust LTS case for testing against latest release and master

Makefile, cmd/policy.go, cmd/prs.go, policy/policy.go
=> Trivial diffs are sometimes required

policy/templates/subtemplates/auto/api-tests.gotmpl, policy/templates/subtemplates/auto/ui-tests.gotmpl
Since there are no breaking changes, this should be fine.
If there is a breaking change in the future, it will have to be handled in the templates.
=> Fetch latest tyk-ci auto

policy/templates/releng/.github/workflows/release.yml.d/auto-test.gotmpl, policy/templates/releng/.github/workflows/release.yml.d/goreleaser.gotmpl
We can switch to larger m-2 machine and check how it will impact performance and our costs in github
=> Change machine to larger in release job template

.github/workflows/release.yml, config/config.yaml, policy/templates/releng/.github/workflows/release.yml.d/goreleaser.gotmpl, policy/templates/releng/.github/workflows/release.yml.d/smoke-tests.gotmpl
=> [SYSE-350] release-5.3 to be maintained by automation

policy/controller.go, policy/controller_test.go, policy/templates/subtemplates/auto/auto-test.gotmpl
- Release v1.8
- Adds cache_db (redis) as output parameter for controller 
- Adds cache_db (redis) as input parameter for matrix
- Modifies the command for env up adding cache db
=> Update templates to latest DB changes

policy/app/index.html
=> add distro rendering

policy/templates/distroless/ci/Dockerfile.distroless
https://github.com/TykTechnologies/portal/pull/1339
=> Fix Portal Dockerfile.distroless

policy/templates/releng/.github/workflows/release.yml.d/goreleaser.gotmpl, policy/templates/releng/.github/workflows/release.yml.d/smoke-tests.gotmpl, policy/templates/subtemplates/auto/auto-test.gotmpl
Prevents tests execution when PR is on draft mode
=> QA-1526/Do not execute tests on draft pr

policy/templates/subtemplates/auto/auto-test.gotmpl
Make all tests to be executed on m2 machines
=> Make all tests jobs run on m2 machines

policy/templates/subtemplates/auto/auto-test.gotmpl
Adding back the upload of report to S3 and posting the link in the github on action results page
=> [QA-1534] UI report S3 upload

config/config.yaml
=> TT-13075 EDP Go 1.22 upgrade

config/config.yaml, policy/tui.go, policy/variations.go
=> distroless for 5.5 and 5.6

config/config.yaml, policy/templates/distroless/ci/Dockerfile.distroless, policy/templates/releng/.github/workflows/release.yml.d/goreleaser.gotmpl, policy/templates/subtemplates/auto/auto-test.gotmpl, policy/templates/subtemplates/goreleaser.yml.d/builds.gotmpl, policy/templates/subtemplates/goreleaser.yml.d/cgo_builds.gotmpl, policy/templates/subtemplates/goreleaser.yml.d/nfpm.gotmpl
This change adds new set of EE artifacts, for both deb/rpm and docker images.
=> Add EE builds

policy/templates/subtemplates/auto/auto-test.gotmpl, policy/templates/test-square/.github/workflows/test-square.yml
Update tyk-pro repo URL and make tests in tyk-pro use m2 machines
=> Update tyk-pro repo URL

cmd/cmdtest/policy/commands.ct, policy/controller.go, policy/controller_test.go, policy/templates/subtemplates/auto/auto-test.gotmpl
We should use tyk-ee image of GW instead of tyk
=> Replace tyk with tyk-ee

cmd/policy.go, policy/templates/releng/.github/workflows/release.yml.d/goreleaser.gotmpl
=> policy match uses tyk-ee

config/config.yaml
Upgrade gateway and dashboard to go 1.23.
=> [TT-13723] Update to Go 1.23

config/config.yaml, policy/schemas/goreleaser.json, policy/templates/releng/ci/goreleaser/goreleaser.yml, policy/templates/subtemplates/goreleaser.yml.d/builds.gotmpl
- **fips builds go to ee, pump does not have an ee build**
- **Fix deprecated goreleaser config**
=> [SYSE-372] Promote to the correct repos

policy/templates/subtemplates/auto/auto-test.gotmpl
Adding timeout for UI and API test execution
=> Add timeout for test execution
